name: Deploy Frontend com Terraform + Upload para S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init e Apply (cria o bucket e configura site)
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve -var="bucket_name=${{ secrets.S3_BUCKET }}"

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Instalar dependências do Angular
        run: npm ci

      - name: Build do Angular com configuração DEV
        run: npx ng build --configuration=dev

      - name: Upload dos arquivos Angular para o S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: sa-east-1
          SOURCE_DIR: dist/validador-senha-frontend